pr:assets:
- assets/**/*
- packages/icons/**/*

pr:bundles:
- packages/bundles/**/*

pr:components:
- packages/react-components/**/*

pr:css:
- packages/css-normalize/**/*
- packages/fonts/**/*
- packages/foundation/**/*
- packages/tachyons/**/*

pr:rfcs:
- packages/rfcs/**/*

pr:tools:
- build/**/*
- jest/**/*
- scripts/**/*
- storybook/**/*

