version: 2.1
aliases:
    - &save-yarn-deps
      name: Save Yarn Package Cache
      key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "storybook/yarn.lock" }}
      paths:
          - ~/.cache/yarn
    - &restore-yarn-deps
      name: Restore Yarn Package Cache
      keys:
          - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "storybook/yarn.lock" }}
jobs:
    build:
        docker:
            - image: cimg/node:16.5.0
        resource_class: large
        working_directory: ~/build
        steps:
            - checkout
            - restore_cache: *restore-yarn-deps
            - run:
                  name: Install Dependencies
                  command: yarn install:pkg --frozen-lockfile
            - save_cache: *save-yarn-deps
            - run:
                  name: Lint
                  command: yarn lint-ci
            - run:
                  name: Setup Packages
                  command: yarn setup:pkg
            - run:
                  name: Build Packages
                  command: yarn build:pkg
            - run:
                  name: Run Jest
                  command: yarn jest-ci
    chromatic:
        parameters:
            exitOnceUploaded:
                type: boolean
                default: true
        docker:
            - image: cimg/node:16.5.0
        working_directory: ~/chromatic
        steps:
            - checkout
            - restore_cache: *restore-yarn-deps
            - run:
                  name: Install Packages Dependencies
                  command: yarn install:pkg --frozen-lockfile
            - run:
                  name: Install Storybook Dependencies
                  command: yarn install:sb --frozen-lockfile
            - save_cache: *save-yarn-deps
            - run:
                  name: Setup Packages
                  command: yarn setup:pkg
            - run:
                  name: Build Packages
                  command: yarn build:pkg
            - run:
                  name: Run chromatic
                  command: yarn chromatic-ci<<# parameters.exitOnceUploaded >> --exit-once-uploaded<</ parameters.exitOnceUploaded >>
workflows:
    version: 2
    github-build:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - master
    github-chromatic:
        jobs:
            - chromatic:
                  filters:
                      branches:
                          ignore:
                              - master
    commit:
        jobs:
            - build:
                  filters:
                      branches:
                          only:
                              - master
    nightly:
        triggers:
            - schedule:
                  cron: "0 0 * * 1-5"
                  filters:
                      branches:
                          only:
                              - master
        jobs:
            - chromatic:
                exitOnceUploaded: false
