# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    install-pkg:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - name: Install Dependencies
              run: yarn install --frozen-lockfile

    lint-eslint:
        runs-on: ubuntu-latest
        needs: install-pkg
        steps:
            - name: Lint Eslint
              run: yarn lint:eslint-ci

    lint-style:
        runs-on: ubuntu-latest
        needs: install-pkg
        steps:
            - name: Lint Stylelint
              run: yarn lint:style-ci

    build:
        runs-on: ubuntu-latest
        needs: install-pkg
        steps:
            - name: Build Packages
              run: yarn build

    test:
        runs-on: ubuntu-latest
        needs: install-pkg
        steps:
            - name: Run Jest
              run: yarn test
